export const backgrounds = [
  require('../../assets/making/background/1.png'),
  require('../../assets/making/background/2.png'),
  require('../../assets/making/background/3.png'),
  require('../../assets/making/background/4.png'),
  require('../../assets/making/background/5.png'),
  require('../../assets/making/background/6.png'),
  require('../../assets/making/background/7.png'),
  require('../../assets/making/background/8.png'),
  require('../../assets/making/background/9.png'),
  require('../../assets/making/background/10.png'),
  require('../../assets/making/background/11.png'),
  require('../../assets/making/background/12.png'),
  require('../../assets/making/background/13.png'),
  require('../../assets/making/background/14.png'),
  require('../../assets/making/background/15.png'),
  require('../../assets/making/background/16.png'),
  require('../../assets/making/background/17.png'),
  require('../../assets/making/background/18.png'),
  require('../../assets/making/background/19.png'),
  require('../../assets/making/background/20.png'),
  require('../../assets/making/background/21.png'),
];

export const frames = {
  _1t1: [
    require('../../assets/making/frame/1t1/1_1t1.png'),
    require('../../assets/making/frame/1t1/2_1t1.png'),
    require('../../assets/making/frame/1t1/3_1t1.png'),
    require('../../assets/making/frame/1t1/4_1t1.png'),
    require('../../assets/making/frame/1t1/5_1t1.png'),
    require('../../assets/making/frame/1t1/6_1t1.png'),
    require('../../assets/making/frame/1t1/7_1t1.png'),
    require('../../assets/making/frame/1t1/8_1t1.png'),
    require('../../assets/making/frame/1t1/9_1t1.png'),
    require('../../assets/making/frame/1t1/10_1t1.png'),
    require('../../assets/making/frame/1t1/11_1t1.png'),
    require('../../assets/making/frame/1t1/12_1t1.png'),
    require('../../assets/making/frame/1t1/13_1t1.png'),
    require('../../assets/making/frame/1t1/14_1t1.png'),
  ],
  _4t3: [
    require('../../assets/making/frame/4t3/1_4t3.png'),
    require('../../assets/making/frame/4t3/2_4t3.png'),
    require('../../assets/making/frame/4t3/3_4t3.png'),
    require('../../assets/making/frame/4t3/4_4t3.png'),
    require('../../assets/making/frame/4t3/5_4t3.png'),
    require('../../assets/making/frame/4t3/6_4t3.png'),
    require('../../assets/making/frame/4t3/7_4t3.png'),
    require('../../assets/making/frame/4t3/8_4t3.png'),
    require('../../assets/making/frame/4t3/9_4t3.png'),
    require('../../assets/making/frame/4t3/10_4t3.png'),
    require('../../assets/making/frame/4t3/11_4t3.png'),
    require('../../assets/making/frame/4t3/12_4t3.png'),
    require('../../assets/making/frame/4t3/13_4t3.png'),
    require('../../assets/making/frame/4t3/14_4t3.png'),
  ],
};
